export const CATALOG_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const PRODUCT_ROUTE = '/product'
export const ABOUT_ROUTE = '/about'
export const CONTACTS_ROUTE = '/contacts'
export const DELIVERY_ROUTE = '/delivery'
export const SHOWROOMS_ROUTE = 'Showrooms'